// awaitEvent
// buildTransformationMatrix
// buildTransformationMatrix3
// cellArray
// changeStructureIdentifier
// closeStructure
// composeMatrix
// composeMatrix3
// composeTransformationMatrix
// composeTransformationMatrix3
// copyAllElementsFromStructure
// deleteAllStructures
// deleteElement
// deleteElementsBetweenLabels
// deleteStructure
// deleteStructureNetwork

// emptyStructure
// evalueateViewMappingMatrix
// evaluateViewMappingMatrix3
// evaluateViewOrientationMatrix
// evaluateViewOrientationMatrix3
// executeStructure

// fillArea
// fillArea3
// fillAreaSet
// fillCircle
// fillCircleArc
// fillEllipse
// fillEllipseArc
// fillRectangle

// generalizedDrawingPrimitive
// getChoice
// getLocator
// getLocator3
// getPick
// getPixel
// getString
// getStroke
// getValuator

// initializeChoice
// initializeLocator
// initializePick
// initializeString
// initializeStroke
// initializeValuator
// inquire

// label

// offsetElementPointer
// openStructure

// polyline
// polyline3
// polymarker
// postStructure

// requestChoice
// requestLocator
// requestPick
// requestString
// requestStroke
// requestValuator
// rotate
// rotateX
// rotateY
// rotateZ

// sampleChoice
// sampleLocator
// samplePick
// sampleString
// sampleStroke
// sampleValuator
// scale
// scale3
// setCharacterExpansionFactor
// setCharacterHeight
// setCharacterSpacing
// setCharacterUpVector
// setChoiceMode
// setColorRepresentation
// setEditMode
// setElementPointer
// setElementPointerAtLabel
// setHighlightingFilter
// setHLHSRidentifier
// setIndividualASF
// setInteriorColorIndex
// setInteriorIndex
// setInteriorRepresentation
// setInteriorStyle
// setInteriorStyleIndex
// setInvisibilityFilter
// setLinetype
// setLinewidthScaleFactor
// setLocalTransformation
// setLocalTransformation3
// setLocatorMode
// setMarkerSizeScaleFactor
// setMarkerType
// setPatternReferencePoint
// setPatternRepresentation
// setPatternSize
// setPickFilter
// setPickIdentifier
// setPickMode
// setPixel
// setPolylineColorIndex
// setPolylineIndex
// setPolylineRepresentation
// setPolymarkerColorINdex
// setPolymarkerIndex
// setPolymarkerRepresentation
// setStringMode
// setStrokeMode
// setTextAlignment
// setTextColorIndex
// setTextFont
// setTextIndex
// setTextMode
// setTextPath
// setTextPrecision
// setTextRepresentation
// setValuatorMode
// setViewIndex
// setViewRepresentation
// setViewRepresentation3
// setViewTransformationInputPriority
// setWorkstationViewport
// setWorkstationViewport3
// setWorkstationWindow
// setWorkstationWindow3

// text
// text3
// transformPoint
// transformPoint3
// translate
// translate3

// unpostAllStructure
// unpostStructure